algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

i, n1, n2: inteiro

inicio
escreval("Digite n1: ")
leia(n1)
escreval("Digite n2: ")
leia(n2)

para i de n1 ate n2 passo 1 faca
  escreval (i)
fimpara


fimalgoritmo