algoritmo "Múltiplos"
// Disciplina  :  Lógica de Programação
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

n,i: inteiro

inicio
escreval("Insira um número: ")
leia(n)
i:= 2
enquanto (i <= 10) faca
    escreval (n * i)
    i:= i+1
fimenquanto


fimalgoritmo