algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
i,n,x: real

inicio
i:=1
escreval("Escreva até qual número você quer somar: ")
leia(x)
enquanto (i<x) faca
    i:=i+1
fimenquanto
n:= (i+1) * (i/2)
escreval(n)

fimalgoritmo