algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

n,i: inteiro

inicio

escreval("Escreva n: ")
leia(n)
i:=0

enquanto (i<n) faca
    se (i mod 2 = 0 ) entao
        escreval(i)
    fimse
    i:= i +1

fimenquanto

fimalgoritmo